DATA.people.push(...[
  /* ---- Julio-Claudian era ---- */
  {id:"varus", displayName:"Quinctilius Varus", fullName:"Publius Quinctilius Varus", alternateNames:["Varus"], year:-46, dynasty:"julioClaudian",
   role:"Governor who lost three legions", bio:"Augustus's kinsman by marriage and governor of Germania. Lured by Arminius into the Teutoburg Forest (AD 9), he lost legions XVII, XVIII, and XIX and fell on his sword — a catastrophe that fixed the Rhine as Rome's German frontier.",
   njclNote:"'Quinctili Varus, give me back my legions!' — Augustus's cry (Suetonius). Teutoburg AD 9 is THE landmark defeat of the early Empire.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["arminius","augustus"], powerLinks:[],
   tags:["military","dynasty"], sources:["Wikipedia: Publius Quinctilius Varus","Britannica: Publius Quinctilius Varus"]},
  {id:"arminius", displayName:"Arminius", fullName:"Arminius (Hermann)", alternateNames:["Hermann","Armin"], year:-17, dynasty:"julioClaudian",
   role:"Cheruscan war-leader; victor of Teutoburg", bio:"Cheruscan noble who served in the Roman auxilia and held citizenship and equestrian rank — then turned on Rome. He engineered the ambush that destroyed Varus's three legions in the Teutoburg Forest (AD 9); Germanicus later campaigned against him, and he was murdered by his own kin in AD 21.",
   njclNote:"The architect of Teutoburg — his victory kept Germany east of the Rhine free of Roman rule. Legion numbers XVII/XVIII/XIX were never reused.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["varus","augustus","germanicus","tiberius"], powerLinks:[],
   tags:["military"], sources:["Wikipedia: Arminius","Britannica: Arminius"]},
  {id:"caratacus", displayName:"Caratacus", fullName:"Caratacus", alternateNames:["Caractacus","Caradog"], year:10, dynasty:"julioClaudian",
   role:"British resistance leader", bio:"Son of Cunobelinus who led British resistance to the invasion of AD 43 for eight years, rallying the Silures and Ordovices of Wales. Defeated by the governor Ostorius Scapula (51), he was betrayed by Queen Cartimandua of the Brigantes and sent to Rome — where his proud speech so impressed Claudius that the emperor pardoned him.",
   njclNote:"His speech before Claudius (Tacitus, Annals 12) and the Brigantes' betrayal are standard exam material.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["claudius"], powerLinks:[],
   tags:["military"], sources:["Wikipedia: Caratacus","Tacitus, Annals"]},
  {id:"boudicca", displayName:"Boudicca", fullName:"Boudicca (Boadicea)", alternateNames:["Boadicea","Boudica"], year:30, dynasty:"julioClaudian",
   role:"Iceni queen; leader of the great British revolt", bio:"Queen of the Iceni; after her husband Prasutagus died, Rome flogged her and raped her daughters. Her revolt (AD 60/61) burned Camulodunum, Londinium, and Verulamium and killed tens of thousands before Suetonius Paulinus crushed her at the Battle of Watling Street; she died soon after, reportedly by poison.",
   njclNote:"The greatest provincial revolt of Nero's reign — know the three destroyed towns and Watling Street.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["nero","suetonius-paulinus"], powerLinks:[],
   tags:["military"], sources:["Wikipedia: Boudica","Britannica: Boudicca"]},
  {id:"suetonius-paulinus", displayName:"Suetonius Paulinus", fullName:"Gaius Suetonius Paulinus", alternateNames:[], year:10, dynasty:"julioClaudian",
   role:"Governor who crushed Boudicca", bio:"Governor of Britain (58–61) who was assaulting the Druid stronghold of Mona (Anglesey) when Boudicca rose behind him; he raced back and destroyed her army at Watling Street (61). He later commanded on Otho's side in 69.",
   njclNote:"Classic confusion alert: Suetonius the GENERAL beat Boudicca; Suetonius the AUTHOR wrote the Twelve Caesars. Different men.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["boudicca","nero","otho"], powerLinks:[],
   tags:["military"], sources:["Wikipedia: Gaius Suetonius Paulinus","Tacitus, Annals"]},
  {id:"narcissus", displayName:"Narcissus (freedman)", fullName:"Tiberius Claudius Narcissus", alternateNames:["Narcissus"], year:10, dynasty:"julioClaudian",
   role:"Claudius's powerful freedman (ab epistulis)", bio:"Imperial freedman who ran Claudius's correspondence (ab epistulis) and amassed fabulous wealth — one of the 'freedmen who ruled the emperor.' He engineered the execution of the empress Messalina (48), opposed Agrippina the Younger, and was killed by her shortly after Claudius died (54).",
   njclNote:"The freedmen Narcissus (letters) and Pallas (finance) embody 'Claudius ruled by his slaves' — a Tacitean/Suetonian staple.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["claudius","messalina","agrippina-younger","pallas"], powerLinks:[],
   tags:["dynasty","succession"], sources:["Wikipedia: Tiberius Claudius Narcissus"]},
  {id:"pallas", displayName:"Pallas (freedman)", fullName:"Marcus Antonius Pallas", alternateNames:["Pallas"], year:15, dynasty:"julioClaudian",
   role:"Claudius's finance freedman (a rationibus)", bio:"Freedman of Antonia Minor, then Claudius's treasury secretary (a rationibus) and ally — ancient sources say lover — of Agrippina the Younger, whose marriage and Nero's adoption he promoted. Immensely rich; Nero dismissed him (55) and later had him killed for his fortune.",
   njclNote:"Pair with Narcissus as the two great Claudian freedmen; his fall marks Agrippina's weakening hold on Nero.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["claudius","agrippina-younger","nero","narcissus"], powerLinks:[],
   tags:["dynasty","succession"], sources:["Wikipedia: Marcus Antonius Pallas"]},
  {id:"corbulo", displayName:"Corbulo", fullName:"Gnaeus Domitius Corbulo", alternateNames:[], year:7, dynasty:"julioClaudian",
   role:"Nero's great eastern general", bio:"Rome's finest commander of the mid-1st century: restored discipline on the Rhine (47) and settled the Armenian question in the East (58–63), taking Artaxata and Tigranocerta and crowning Tigranes VI. His popularity made Nero suspicious; summoned to Greece, he was forced to commit suicide (67), reportedly crying 'axios' — 'I deserved better.'",
   njclNote:"The empire's best general destroyed by a jealous emperor — his settlement of Armenia held for decades.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["nero"], powerLinks:[],
   tags:["military"], sources:["Wikipedia: Gnaeus Domitius Corbulo","Tacitus, Annals"]},
  {id:"burrus", displayName:"Afranius Burrus", fullName:"Sextus Afranius Burrus", alternateNames:["Burrus"], year:1, dynasty:"julioClaudian",
   role:"Praetorian prefect; Nero's co-guide with Seneca", bio:"Praetorian prefect from 51 who, with Seneca, steered Nero through his stable early years — the 'Quinquennium Neronis.' He resisted Nero's matricidal turn until his death in 62 (of a throat ailment; Romans suspected poison).",
   njclNote:"Burrus + Seneca = the 'good' influences; his death (62) opens the door to Tigellinus and Nero's worst period.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["nero","seneca","agrippina-younger"], powerLinks:["praetorian-guard"],
   tags:["military","dynasty"], sources:["Wikipedia: Sextus Afranius Burrus","Tacitus, Annals"]},
  {id:"poppaea", displayName:"Poppaea Sabina", fullName:"Poppaea Sabina", alternateNames:["Poppaea"], year:30, dynasty:"julioClaudian",
   role:"Nero's ambitious second wife", bio:"Beautiful, cultivated noblewoman who left Otho for Nero and became empress (62); Tacitus says she pushed for the removal of Agrippina the Younger and the innocent Octavia. Nero allegedly killed her with a kick while pregnant (65) — then deified her.",
   njclNote:"Remember the triangle: Nero took Poppaea from Otho (packed off to govern Lusitania), then killed her in a rage.",
   biologicalLinks:[], maritalLinks:["otho","nero"], adoptiveLinks:[], associateLinks:["agrippina-younger","octavia","tigellinus"], powerLinks:[],
   tags:["dynasty","succession"], sources:["Wikipedia: Poppaea Sabina","Tacitus, Annals"]},
  {id:"tigellinus", displayName:"Tigellinus", fullName:"Gaius Ofonius Tigellinus", alternateNames:["Ophonius Tigellinus"], year:10, dynasty:"julioClaudian",
   role:"Nero's notorious Praetorian prefect", bio:"Exiled under Caligula for adultery with Agrippina the Younger, he returned to become Nero's praetorian prefect (62) — the 'bad advisor' who indulged the emperor's vices, engineered the destruction of Octavia, and prosecuted the Pisonian witch-hunt. Abandoned Nero in 68, then was forced to suicide by Otho at Sinuessa (69).",
   njclNote:"The villain-prefect counterpart to the good Burrus — his rise (62) marks the start of Nero's tyrannical phase.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["nero","poppaea"], powerLinks:["praetorian-guard"],
   tags:["military","dynasty"], sources:["Wikipedia: Tigellinus","Tacitus, Annals"]},
  {id:"thrasea-paetus", displayName:"Thrasea Paetus", fullName:"Publius Clodius Thrasea Paetus", alternateNames:["Thrasea"], year:20, dynasty:"julioClaudian",
   role:"Stoic martyr of Nero's reign", bio:"Senator and head of the 'Stoic opposition' who protested Nero by principled absence — walking out of the Senate's flattery of the matricide. Condemned in the treason trials of 66 (with Barea Soranus), he opened his veins: 'we are making a libation to Jupiter the Liberator.'",
   njclNote:"The Stoic martyrs (Thrasea, Barea Soranus, Seneca, Lucan) all fall 65–66 — the price of the Pisonian Conspiracy's aftermath.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["nero","seneca"], powerLinks:[],
   tags:["religion","dynasty"], sources:["Wikipedia: Thrasea Paetus","Tacitus, Annals"]},
  {id:"vindex", displayName:"Gaius Julius Vindex", fullName:"Gaius Julius Vindex", alternateNames:["Vindex"], year:68, dynasty:"julioClaudian",
   role:"Governor whose revolt doomed Nero", bio:"Romanized Aquitanian prince and governor of Gallia Lugdunensis who revolted against Nero in spring 68, championing Galba of Spain. Loyal legions under Verginius Rufus crushed him at Vesontio (Besançon), but the revolt cracked Nero's support — within months the emperor was dead.",
   njclNote:"Vindex's failed revolt (68) is the trigger of the end: it set Galba's march on Rome in motion.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["nero","galba"], powerLinks:[],
   tags:["military","civil-war"], sources:["Wikipedia: Gaius Julius Vindex","Cassius Dio, Roman History"]},

  /* ---- Year of the Four Emperors ---- */
  {id:"mucianus", displayName:"Licinius Mucianus", fullName:"Gaius Licinius Mucianus", alternateNames:["Mucianus"], year:30, dynasty:"fourEmperors",
   role:"Vespasian's partner in the coup", bio:"Suave governor of Syria who set aside his rivalry with Vespasian to become the kingmaker of 69: he provided legitimacy, money, and the army that marched on Italy via the Balkans and secured Rome in December 69. He then effectively governed the city until Vespasian arrived.",
   njclNote:"The 'brains' behind Vespasian's takeover — Antonius Primus won the battles, Mucianus won the politics.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["vespasian","antonius-primus","tiberius-julius-alexander","julius-civilis"], powerLinks:[],
   tags:["military","civil-war","succession"], sources:["Wikipedia: Gaius Licinius Mucianus","Tacitus, Histories"]},
  {id:"antonius-primus", displayName:"Antonius Primus", fullName:"Marcus Antonius Primus", alternateNames:["Primus"], year:30, dynasty:"fourEmperors",
   role:"Flavian general; victor of 2nd Bedriacum", bio:"Fiery legionary legate who, without waiting for orders, led the Danubian legions into Italy for Vespasian, smashed Vitellius's army at the second battle of Bedriacum/Cremona (Oct 69), and took Rome that December. He expected supreme reward — Vespasian sidelined him instead.",
   njclNote:"2nd Bedriacum (Oct 69) decided the civil war; the sack of Cremona that followed appalled even Romans.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["vespasian","mucianus","vitellius"], powerLinks:[],
   tags:["military","civil-war"], sources:["Wikipedia: Marcus Antonius Primus","Tacitus, Histories"]},
  {id:"julius-civilis", displayName:"Gaius Julius Civilis", fullName:"Gaius Julius Civilis", alternateNames:["Civilis","Julius Civilis"], year:25, dynasty:"fourEmperors",
   role:"Leader of the Batavian revolt", bio:"One-eyed Batavian noble of royal blood who exploited the chaos of 69 to raise a massive revolt (69–70): Batavian auxiliaries, the Rhine legions' German cohorts, and Gallic allies under the Treveri Julius Classicus and Julius Tutor dreamed of an 'empire of the Gauls.' Petillius Cerialis defeated the coalition; Civilis bargained for amnesty and vanished from history.",
   njclNote:"The Batavian revolt is Tacitus's great set-piece in the Histories — a provincial uprising disguised as Flavian loyalism.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["vespasian","mucianus"], powerLinks:[],
   tags:["military","civil-war"], sources:["Wikipedia: Gaius Julius Civilis","Tacitus, Histories"]},

  /* ---- Flavian era ---- */
  {id:"tiberius-julius-alexander", displayName:"Tiberius Julius Alexander", fullName:"Tiberius Julius Alexander", alternateNames:[], year:20, dynasty:"flavian",
   role:"Prefect of Egypt; Titus's chief of staff", bio:"Renegade Alexandrian Jew (nephew of the philosopher Philo) who as prefect of Egypt proclaimed Vespasian emperor on 1 July 69 — the first legions to do so — then served as Titus's senior general through the siege of Jerusalem (70).",
   njclNote:"An apostate Jew who crowned a dynasty and directed the siege of his own people's holy city — a certamen favorite.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["titus","vespasian","mucianus"], powerLinks:[],
   tags:["military","religion"], sources:["Wikipedia: Tiberius Julius Alexander","Josephus, The Jewish War"]},
  {id:"agricola", displayName:"Agricola", fullName:"Gnaeus Julius Agricola", alternateNames:["Julius Agricola"], year:40, dynasty:"flavian",
   role:"Conqueror of Britain; Tacitus's father-in-law", bio:"Governor of Britain (77/78–84/85) who completed the conquest of Wales, including the Druid island of Mona, carried Roman arms deep into Scotland, and smashed the Caledonians under Calgacus at Mons Graupius (83/84). Domitian recalled him and never again employed him; his life is the subject of Tacitus's Agricola.",
   njclNote:"Mons Graupius ends his governorship; 'they make a desert and call it peace' is Calgacus's speech against him in Tacitus.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["tacitus","domitian","calgacus"], powerLinks:[],
   tags:["military"], sources:["Wikipedia: Gnaeus Julius Agricola","Tacitus, Agricola"]},
  {id:"calgacus", displayName:"Calgacus", fullName:"Calgacus (Galgacus)", alternateNames:["Galgacus"], year:83, dynasty:"flavian",
   role:"Caledonian leader at Mons Graupius", bio:"Chieftain who rallied the Caledonian tribes for the climactic battle against Agricola at Mons Graupius (83 or 84). He exists only in Tacitus, whose pre-battle speech gives him the immortal line 'ubi solitudinem faciunt, pacem appellant' — 'they make a desolation and call it peace.'",
   njclNote:"Know the quote and its target (Roman imperialism); whether Calgacus was real or Tacitus's mouthpiece is a classic debate.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["agricola"], powerLinks:[],
   tags:["military"], sources:["Wikipedia: Calgacus","Tacitus, Agricola"]},
  {id:"josephus", displayName:"Josephus", fullName:"Titus Flavius Josephus (b. Yosef ben Matityahu)", alternateNames:["Flavius Josephus","Joseph ben Matthias"], year:37, dynasty:"flavian",
   role:"Jewish historian of the revolt", bio:"Jewish priest who commanded Galilee in the Great Revolt, was captured at Jotapata (67), and predicted Vespasian would become emperor — winning Flavian patronage and Roman citizenship. He wrote The Jewish War, Antiquities of the Jews, Against Apion, and his Life, our main narrative for the revolt and for 1st-century Judaism.",
   njclNote:"Defender-turned-defector: he witnessed Masada's story (via survivors) and the destruction of the Temple under Titus (70).",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["vespasian","titus"], powerLinks:[],
   tags:["literature","religion","military"], sources:["Wikipedia: Josephus","Britannica: Flavius Josephus"]},
  {id:"pliny-elder", displayName:"Pliny the Elder", fullName:"Gaius Plinius Secundus", alternateNames:["Pliny"], year:23, dynasty:"flavian",
   role:"Encyclopedist; died in the Vesuvius eruption", bio:"Tireless equestrian official and author of the 37-book Naturalis Historia, the great surviving Roman encyclopedia of nature, art, and technology. Commanding the fleet at Misenum in August 79, he sailed toward the Vesuvius eruption to investigate and to rescue — and died at Stabiae.",
   njclNote:"His nephew's letters to Tacitus narrate both the eruption and his death — and are our source for distinguishing him from Pliny the Younger.",
   biologicalLinks:["pliny-younger"], maritalLinks:[], adoptiveLinks:["pliny-younger"], associateLinks:["vespasian","titus"], powerLinks:[],
   tags:["literature","military"], sources:["Wikipedia: Pliny the Elder","Britannica: Pliny the Elder"]},
  {id:"quintilian", displayName:"Quintilian", fullName:"Marcus Fabius Quintilianus", alternateNames:["Quintilianus"], year:35, dynasty:"flavian",
   role:"Rome's first state professor of rhetoric", bio:"Spanish-born rhetorician appointed by Vespasian to Rome's first publicly funded chair of Latin rhetoric; among his pupils were Pliny the Younger and, reputedly, the grandnephews Domitian designated as heirs. His Institutio Oratoria — the complete training of the 'good man skilled in speaking' — is the fullest surviving ancient treatise on rhetoric and education.",
   njclNote:"Vir bonus dicendi peritus ('a good man skilled in speaking') is his famous definition of the orator's aim.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["domitian","vespasian","pliny-younger","martial"], powerLinks:[],
   tags:["literature"], sources:["Wikipedia: Quintilian","Britannica: Quintilian"]},
  {id:"martial", displayName:"Martial", fullName:"Marcus Valerius Martialis", alternateNames:["Martialis"], year:40, dynasty:"flavian",
   role:"Master of the epigram", bio:"Bilbilis-born poet whose fourteen books of Epigrams skewer Roman life with wit and venom — the form's definitive practitioner. His Liber Spectaculorum celebrated the opening games of the Colosseum (80); patronized under Domitian, he faded under later emperors and retired to Spain.",
   njclNote:"Epigrams = Martial; his Colosseum poems tie him to the Flavian building program.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["domitian","pliny-younger","juvenal","quintilian"], powerLinks:[],
   tags:["literature"], sources:["Wikipedia: Martial","Britannica: Martial"]},

  /* ---- Nerva-Antonine era ---- */
  {id:"tacitus", displayName:"Tacitus", fullName:"Publius (or Gaius) Cornelius Tacitus", alternateNames:["Cornelius Tacitus"], year:56, dynasty:"nervaAntonine",
   role:"Rome's greatest historian", bio:"Senator, consul (97), and proconsul of Asia whose works define our picture of the early Empire: Agricola and Germania (both 98), the Histories (69–96), and the Annals (Tiberius to Nero). His trenchant, pessimistic style anatomizes power under the Caesars — and he married Agricola's daughter.",
   njclNote:"Annals = Tiberius→Nero; Histories = the civil wars. Don't confuse him with the emperor Tacitus (275–276) or Suetonius the biographer.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["pliny-younger","agricola","trajan"], powerLinks:[],
   tags:["literature"], sources:["Wikipedia: Tacitus","Britannica: Tacitus"]},
  {id:"pliny-younger", displayName:"Pliny the Younger", fullName:"Gaius Plinius Caecilius Secundus", alternateNames:["Pliny"], year:61, dynasty:"nervaAntonine",
   role:"Letter-writer; Trajan's governor in Bithynia", bio:"Nephew and adopted son of the encyclopedist; a career senator whose polished Letters are a key window on the era — including two to Tacitus describing Vesuvius and his uncle's death, and the famous correspondence with Trajan (X.96–97) on how to treat Christians, our earliest official statement of Roman policy toward them.",
   njclNote:"The Christians letter to Trajan (c. 112) is a staple primary source: 'the contagion of this superstition.'",
   biologicalLinks:["pliny-elder"], maritalLinks:[], adoptiveLinks:["pliny-elder"], associateLinks:["trajan","tacitus"], powerLinks:[],
   tags:["literature","christianity"], sources:["Wikipedia: Pliny the Younger","Britannica: Pliny the Younger"]},
  {id:"suetonius", displayName:"Suetonius", fullName:"Gaius Suetonius Tranquillus", alternateNames:["Suetonius Tranquillus"], year:69, dynasty:"nervaAntonine",
   role:"Biographer of the Twelve Caesars", bio:"Equestrian scholar and imperial secretary (ab epistulis) dismissed by Hadrian; his De Vita Caesarum — Julius Caesar through Domitian — supplies the gossip, omens, and anecdotes behind most 'facts' students learn about the early emperors.",
   njclNote:"Twelve Caesars = Julius to Domitian. Keep straight: Suetonius the biographer vs. Suetonius Paulinus the general who beat Boudicca.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["hadrian","pliny-younger"], powerLinks:[],
   tags:["literature"], sources:["Wikipedia: Suetonius","Britannica: Suetonius"]},
  {id:"juvenal", displayName:"Juvenal", fullName:"Decimus Junius Juvenalis", alternateNames:[], year:55, dynasty:"nervaAntonine",
   role:"Satirist of imperial Rome", bio:"Author of sixteen Satires pouring savage verse on vice, patronage, wealth, and foreigners under Domitian through Hadrian. His lines live on: 'panem et circenses' (bread and circuses), 'quis custodiet ipsos custodes' (who watches the watchmen), 'difficile est saturam non scribere.'",
   njclNote:"'Bread and circuses' — Juvenal's phrase for how emperors bought off the Roman mob — is still the standard quote.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["martial"], powerLinks:[],
   tags:["literature"], sources:["Wikipedia: Juvenal","Britannica: Juvenal"]},
  {id:"fronto", displayName:"Fronto", fullName:"Marcus Cornelius Fronto", alternateNames:["Marcus Cornelius Fronto"], year:100, dynasty:"nervaAntonine",
   role:"Rhetoric tutor of Marcus Aurelius", bio:"Numidian-born orator and suffect consul (143) who taught rhetoric to the future emperor Marcus Aurelius (and Lucius Verus). Their surviving correspondence records the prince's slow turn from eloquence to philosophy — and a treasury of everyday Antonine detail.",
   njclNote:"The Fronto–Marcus letters are our best look inside the imperial schoolroom and at official 'Latin eloquence' prized by the court.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["marcus-aurelius","lucius-verus"], powerLinks:[],
   tags:["literature"], sources:["Wikipedia: Marcus Cornelius Fronto","Britannica: Fronto"]},
  {id:"apuleius", displayName:"Apuleius", fullName:"Lucius Apuleius (of Madaura)", alternateNames:["Apuleius of Madaurus"], year:124, dynasty:"nervaAntonine",
   role:"Novelist; author of The Golden Ass", bio:"North African rhetorician and Platonist, tried for witchcraft (his Apologia is a courtroom speech for the ages). His Metamorphoses — The Golden Ass — is the only Latin novel to survive complete: Lucius, transformed into a donkey, wanders through magic, bawdry, and finally the mysteries of Isis.",
   njclNote:"The Golden Ass = the only complete Roman novel; the Cupid and Psyche tale inside it is its most famous inset.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:[], powerLinks:[],
   tags:["literature","religion"], sources:["Wikipedia: Apuleius","Britannica: Apuleius"]},
  {id:"galen", displayName:"Galen", fullName:"Galen of Pergamon (Claudius Galenus)", alternateNames:["Galenus"], year:129, dynasty:"nervaAntonine",
   role:"Physician of the emperors", bio:"Pergamene doctor who apprenticed on gladiator wounds, then served the Antonine court (attending Marcus Aurelius and Commodus). His hundreds of treatises codified anatomy, physiology, and the humoral theory — the authority in Western and Islamic medicine for nearly 1,500 years.",
   njclNote:"Second only to Hippocrates as the ancient medical name; his errors (learned from animal dissection) went unchallenged until Vesalius.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["marcus-aurelius"], powerLinks:[],
   tags:["literature"], sources:["Wikipedia: Galen","Britannica: Galen"]},
  {id:"epictetus", displayName:"Epictetus", fullName:"Epictetus of Hierapolis", alternateNames:["Epiktetos"], year:55, dynasty:"nervaAntonine",
   role:"Stoic philosopher; slave turned teacher", bio:"Born a slave (owned by Nero's freedman Epaphroditus) and lame, he studied under Musonius Rufus, was expelled in Domitian's banishment of philosophers (~89–93), and taught at Nicopolis in Epirus. He wrote nothing; his pupil Arrian published the Discourses and the Enchiridion — 'endure and renounce.'",
   njclNote:"Slave Epictetus and emperor Marcus Aurelius are the two poles of Roman Stoicism — a favorite pairing.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["marcus-aurelius"], powerLinks:[],
   tags:["religion","literature"], sources:["Wikipedia: Epictetus","Britannica: Epictetus"]},

  /* ---- Severan era ---- */
  {id:"cassius-dio", displayName:"Cassius Dio", fullName:"Lucius Cassius Dio Cocceianus", alternateNames:["Dio","Dio Cassius"], year:155, dynasty:"severan",
   role:"Senator-historian of Rome in Greek", bio:"Bithynian senator, twice consul (the second, ~229, alongside Severus Alexander), whose 80-book Roman History in Greek runs from Aeneas to his own day — the fullest surviving continuous narrative of the Republic and early Empire.",
   njclNote:"He is the indispensable source where Tacitus fails (e.g., Claudius's invasion of Britain) — remember Dio wrote in GREEK.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["severus-alexander","septimius-severus"], powerLinks:[],
   tags:["literature"], sources:["Wikipedia: Cassius Dio","Britannica: Cassius Dio"]},
  {id:"papinian", displayName:"Papinian", fullName:"Aemilius Papinianus", alternateNames:["Papinianus"], year:140, dynasty:"severan",
   role:"Jurist martyred by Caracalla", bio:"One of the five great classical jurists, close to Septimius Severus and praetorian prefect. When Caracalla murdered Geta and asked him to justify the crime, he refused — 'parricide is not so easy to defend as to commit' — and was executed (212).",
   njclNote:"His defiance of Caracalla is THE jurist anecdote; chunks of his work were later canonized in Justinian's Digest.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["septimius-severus","caracalla","geta","ulpian"], powerLinks:[],
   tags:["law"], sources:["Wikipedia: Aemilius Papinianus","Britannica: Papinian"]},
  {id:"ulpian", displayName:"Ulpian", fullName:"Domitius Ulpianus", alternateNames:["Ulpianus"], year:170, dynasty:"severan",
   role:"Jurist-prefect killed by his own Guard", bio:"Tyrian jurist whose writings supply roughly a third of Justinian's Digest; as praetorian prefect under Severus Alexander he effectively ran the administration — until the Praetorians murdered him (223/228), chasing him to the palace itself.",
   njclNote:"Papinian and Ulpian are the two jurist martyrs — one killed by an emperor, one by the Guard itself.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["severus-alexander","julia-mamaea","papinian"], powerLinks:["praetorian-guard"],
   tags:["law","military"], sources:["Wikipedia: Ulpian","Britannica: Ulpian"]},
  {id:"tertullian", displayName:"Tertullian", fullName:"Quintus Septimius Florens Tertullianus", alternateNames:["Tertullianus"], year:155, dynasty:"severan",
   role:"First great Latin Christian writer", bio:"Carthaginian rhetorician and jurist's son who forged Christian Latin — his Apologeticus (~197) defends the faith to Rome's magistrates ('the blood of Christians is seed'), and he coined much of the West's theological vocabulary (trinitas). Late in life he joined the puritanical Montanists.",
   njclNote:"'Semen est sanguis Christianorum' — the blood of martyrs is seed. First major Christian author in Latin (vs. Greek fathers).",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:[], powerLinks:[],
   tags:["christianity","religion","literature"], sources:["Wikipedia: Tertullian","Britannica: Tertullian"]},
  {id:"origen", displayName:"Origen", fullName:"Origenes Adamantius", alternateNames:["Origen of Alexandria"], year:185, dynasty:"severan",
   role:"Prolific Alexandrian theologian", bio:"Head of Alexandria's catechetical school and the most prodigious scholar of the early Church — his Hexapla aligned six versions of the Old Testament, and On First Principles attempted a systematic theology. Tortured in the Decian persecution, he died soon after (~253); posterity argued over his orthodoxy for centuries.",
   njclNote:"Eusebius claims he took 'there are eunuchs...' literally — the famous self-castration story attaches to him.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["decius"], powerLinks:[],
   tags:["christianity","religion","literature"], sources:["Wikipedia: Origen","Britannica: Origen"]},

  /* ---- Crisis of the Third Century ---- */
  {id:"shapur-i", displayName:"Shapur I", fullName:"Shapur I (Sasanian Shahanshah)", alternateNames:["Shapur","Sapor"], year:215, dynasty:"crisis",
   role:"Persian shah; captured Valerian alive", bio:"Ardashir's son and second Sasanian king of kings; the gravest foreign threat of the crisis era. He crushed Rome's eastern armies, sacked Antioch, and at Edessa (260) captured the emperor Valerian himself — commemorated in rock reliefs and the Ka'ba-ye Zartosht inscription; Roman captives built his great dams at Shushtar.",
   njclNote:"Valerian = the only Roman emperor ever taken alive in war — by Shapur I at Edessa (260). A guaranteed question.",
   biologicalLinks:["shapur-ii"], maritalLinks:[], adoptiveLinks:[], associateLinks:["valerian","gallienus","odaenathus"], powerLinks:[],
   tags:["military","crisis"], sources:["Wikipedia: Shapur I","Britannica: Shapur I"]},
  {id:"odaenathus", displayName:"Odaenathus", fullName:"Septimius Odaenathus", alternateNames:["Odenathus","Odaenathus of Palmyra"], year:220, dynasty:"crisis",
   role:"Palmyrene king; Rome's eastern client", bio:"Prince of Palmyra who rallied after Valerian's capture, drove Shapur I's armies back across the Euphrates, and was rewarded by Gallienus with command of the East (corrector totius Orientis). Assassinated ~267/268, he left the kingdom — and the imperial gamble — to his widow Zenobia.",
   njclNote:"Husband of Zenobia: HIS victories over Persia are what Palmyra's later breakaway empire was built on.",
   biologicalLinks:[], maritalLinks:["zenobia"], adoptiveLinks:[], associateLinks:["gallienus","shapur-i","valerian"], powerLinks:[],
   tags:["military","crisis","succession"], sources:["Wikipedia: Odaenathus","Britannica: Odaenathus"]},
  {id:"cyprian", displayName:"Cyprian", fullName:"Thascius Caecilius Cyprianus", alternateNames:["Cyprian of Carthage"], year:200, dynasty:"crisis",
   role:"Bishop of Carthage; martyr under Valerian", bio:"Wealthy rhetorician converted ~246 and within two years bishop of Carthage (248). He hid through the Decian persecution, then fought the crisis over the lapsed (those who had sacrificed) — his De unitate ecclesiae champions episcopal unity. Under Valerian's renewed persecution he was beheaded (258), answering 'Deo gratias' at the sentence.",
   njclNote:"First African bishop-martyr; the 'lapsed' controversy after Decius is his defining context.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["decius","valerian"], powerLinks:[],
   tags:["christianity","religion"], sources:["Wikipedia: Cyprian","Britannica: Cyprian"]},

  /* ---- Constantinian era ---- */
  {id:"arius", displayName:"Arius", fullName:"Arius of Alexandria", alternateNames:["Areios"], year:256, dynasty:"constantinian",
   role:"Presbyter behind the Arian heresy", bio:"Alexandrian priest whose teaching — the Son is a created being ('there was a time when he was not') — split the Church just as it was legalized. Condemned at Nicaea (325) and briefly exiled, he was rehabilitated and died suddenly in Constantinople (336), on the eve of a triumphal readmission.",
   njclNote:"Arianism: the Son is created/subordinate — vs. the Nicene homoousios ('same substance'). A whole era of theology in one distinction.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["constantine-i","athanasius"], powerLinks:[],
   tags:["christianity","religion"], sources:["Wikipedia: Arius","Britannica: Arius"]},
  {id:"athanasius", displayName:"Athanasius", fullName:"Athanasius of Alexandria", alternateNames:["Athanasius the Great"], year:296, dynasty:"constantinian",
   role:"Nicene champion; bishop of Alexandria", bio:"Deacon at Nicaea (325), then bishop of Alexandria for 45 turbulent years (328–373) — the indefatigable defender of the homoousios against Arian-leaning emperors, who exiled him five times ('Athanasius contra mundum'). His Festal Letter 39 (367) first listed today's 27-book New Testament canon.",
   njclNote:"Five exiles, four emperors — the archetype of the churchman standing alone against Arianism and the court.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["arius","constantine-i","constantius-ii"], powerLinks:[],
   tags:["christianity","religion"], sources:["Wikipedia: Athanasius of Alexandria","Britannica: Saint Athanasius"]},
  {id:"eusebius-caesarea", displayName:"Eusebius of Caesarea", fullName:"Eusebius Pamphili (of Caesarea)", alternateNames:["Eusebius"], year:260, dynasty:"constantinian",
   role:"Father of Church History", bio:"Bishop of Caesarea (~313–339) whose Ecclesiastical History — the first of its kind — preserved the martyrs, succession lists, and lost documents of the early Church; his panegyrical Life of Constantine is the essential (if flattering) source for the first Christian emperor.",
   njclNote:"Two hats: skeptical scholars mine his History; propagandists quote his Constantine. Know both works.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["constantine-i","arius"], powerLinks:[],
   tags:["christianity","religion","literature"], sources:["Wikipedia: Eusebius","Britannica: Eusebius of Caesarea"]},
  {id:"ulfilas", displayName:"Ulfilas", fullName:"Ulfilas (Wulfila)", alternateNames:["Wulfila","Ulphilas"], year:311, dynasty:"constantinian",
   role:"Apostle to the Goths; Arian missionary", bio:"Cappadocian-Gothic descendant consecrated 'bishop of the Goths' (341) at Antioch; he evangelized beyond the Danube, then in Moesia, inventing the Gothic alphabet to translate the Bible — omitting the war books of Kings 'lest the war-loving Goths be stirred.' His Arian creed became the Goths' Christianity, marking them heretics to Romans for two centuries.",
   njclNote:"Explains why Visigoths & Ostrogoths were ARIAN — it all traces to Ulfilas's mid-4th-century mission.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["constantius-ii"], powerLinks:[],
   tags:["christianity","religion"], sources:["Wikipedia: Ulfilas","Britannica: Ulfilas"]},
  {id:"shapur-ii", displayName:"Shapur II", fullName:"Shapur II 'the Great' (Sasanian Shahanshah)", alternateNames:["Shapur the Great","Sapor II"], year:309, dynasty:"constantinian",
   role:"Persian shah; Julian's nemesis", bio:"Crowned in utero and reigning 70 years (309–379) — the longest Sasanian reign. He besieged Nisibis thrice, stormed Amida (359, an assault Ammianus witnessed), and broke Julian's great invasion; the peace of 363 delivered him Nisibis and five provinces beyond the Tigris.",
   njclNote:"Julian died campaigning against him (363) and Jovian's humiliating treaty followed — pair with Shapur I's capture of Valerian a century earlier.",
   biologicalLinks:["shapur-i"], maritalLinks:[], adoptiveLinks:[], associateLinks:["julian","constantius-ii","jovian","valens"], powerLinks:[],
   tags:["military"], sources:["Wikipedia: Shapur II","Britannica: Shapur II"]},

  /* ---- Theodosian era (incl. Christian Latin authors & fall-of-West) ---- */
  {id:"ammianus-marcellinus", displayName:"Ammianus Marcellinus", fullName:"Ammianus Marcellinus", alternateNames:["Ammianus"], year:330, dynasty:"theodosian",
   role:"Last great Roman historian", bio:"Greek-born staff officer who fought under Constantius II and marched in Julian's Persian disaster (363); retiring to Rome he wrote the Res Gestae (~390s), continuing Tacitus from Nerva to the catastrophe at Adrianople (378) — eyewitness, judicious, tolerant, and the end of classical Latin historiography.",
   njclNote:"His history ENDS at 378 — the falling curtain of the old army; he explicitly continues Tacitus's story.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["julian","constantius-ii","valens"], powerLinks:[],
   tags:["literature","military"], sources:["Wikipedia: Ammianus Marcellinus","Britannica: Ammianus Marcellinus"]},
  {id:"ambrose", displayName:"Ambrose of Milan", fullName:"Aurelius Ambrosius", alternateNames:["Saint Ambrose"], year:340, dynasty:"theodosian",
   role:"Bishop who made an emperor do penance", bio:"Provincial governor acclaimed bishop of Milan (374) while still unbaptized. He bested the pagan Symmachus in the Altar of Victory debates, withstood the Arian court of Valentinian II's mother Justina, baptized Augustine (387), and — most famously — barred Theodosius I from communion after the Thessalonica massacre until he did public penance (390).",
   njclNote:"Theodosius's penance at Milan (390) is THE precedent for 'Church above Caesar' — the Middle Ages' favorite proof-text.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["theodosius-i","symmachus","valentinian-ii","augustine"], powerLinks:[],
   tags:["christianity","religion"], sources:["Wikipedia: Ambrose","Britannica: Saint Ambrose"]},
  {id:"augustine", displayName:"Augustine of Hippo", fullName:"Aurelius Augustinus", alternateNames:["Saint Augustine"], year:354, dynasty:"theodosian",
   role:"Greatest Latin Church Father", bio:"Thagaste-born rhetor and ex-Manichaean converted at Milan (386; baptized by Ambrose), then bishop of Hippo (396). The Confessions invented spiritual autobiography; after the 410 sack he wrote The City of God — Rome's fall weighed against the civitas Dei; he died in 430 as the Vandals besieged Hippo.",
   njclNote:"City of God = the Christian answer to 'Rome fell because it abandoned the gods' — written BECAUSE of Alaric's sack.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["ambrose","jerome"], powerLinks:[],
   tags:["christianity","religion","literature"], sources:["Wikipedia: Augustine of Hippo","Britannica: Saint Augustine"]},
  {id:"jerome", displayName:"Jerome", fullName:"Eusebius Sophronius Hieronymus", alternateNames:["Saint Jerome","Hieronymus"], year:347, dynasty:"theodosian",
   role:"Translator of the Vulgate", bio:"Dalmatian ascetic, secretary to Pope Damasus, then monk of Bethlehem; his Latin translation of the Bible (OT from Hebrew, plus the Gospels) became the Vulgate — Western Christendom's Bible for a millennium. Combative polemicist, correspondent of Augustine, teacher of aristocratic Roman widows.",
   njclNote:"Vulgate = Jerome's Bible — the single most consequential book-production fact of the late Empire.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["augustine"], powerLinks:[],
   tags:["christianity","religion","literature"], sources:["Wikipedia: Jerome","Britannica: Saint Jerome"]},
  {id:"john-chrysostom", displayName:"John Chrysostom", fullName:"John Chrysostom ('Golden-Mouthed')", alternateNames:["Chrysostom","St. John Chrysostom"], year:349, dynasty:"theodosian",
   role:"Greatest preacher of Constantinople", bio:"Antioch-born ascetic whose blazing sermons ('golden-mouthed') carried him to the patriarchate of Constantinople (398). His denunciations of luxury collided with Empress Eudoxia and Patriarch Theophilus of Alexandria; deposed and twice exiled, he died on the forced march to Pityus (407).",
   njclNote:"A bishop destroyed by an EMPRESS this time (Eudoxia) — contrast Ambrose forcing Theodosius's penance.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["arcadius"], powerLinks:[],
   tags:["christianity","religion","literature"], sources:["Wikipedia: John Chrysostom","Britannica: Saint John Chrysostom"]},
  {id:"hypatia", displayName:"Hypatia of Alexandria", fullName:"Hypatia of Alexandria", alternateNames:["Hypatia"], year:355, dynasty:"theodosian",
   role:"Neoplatonist philosopher murdered by a mob", bio:"Daughter of the mathematician Theon and head of Alexandria's Platonic school — the ancient world's most famous woman philosopher, teaching mathematics, astronomy, and Neoplatonism to pagans and Christians alike. In 415 a Christian mob, inflamed by the feud between Patriarch Cyril and Prefect Orestes, murdered her.",
   njclNote:"Her death (415) is the emblem of Alexandria's pagan-Christian street war — she's often cast as the last 'pagan' martyr.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:[], powerLinks:[],
   tags:["literature","religion"], sources:["Wikipedia: Hypatia","Britannica: Hypatia"]},
  {id:"symmachus", displayName:"Quintus Aurelius Symmachus", fullName:"Quintus Aurelius Symmachus", alternateNames:["Symmachus"], year:340, dynasty:"theodosian",
   role:"Last champion of pagan Rome", bio:"The old aristocracy's eloquent spokesman — prefect of Rome (384) and consul (391). His Relatio III petitioned the boy emperor Valentinian II to restore the Altar of Victory to the Senate house; Ambrose's refutation carried the day. He also headed the pagan delegation that crowned Eugenius before Frigidus.",
   njclNote:"Altar of Victory (384): the last great stand of official paganism — Symmachus pleads, Ambrose wins.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["ambrose","valentinian-ii","theodosius-i"], powerLinks:[],
   tags:["religion"], sources:["Wikipedia: Quintus Aurelius Symmachus","Britannica: Quintus Aurelius Symmachus"]},
  {id:"pope-leo-i", displayName:"Pope Leo I the Great", fullName:"Pope Leo I (Leo the Great)", alternateNames:["Leo the Great","Pope Leo"], year:400, dynasty:"theodosian",
   role:"Pope who met Attila; voice of Chalcedon", bio:"Pope (440–461) and the strongest early bishop of Rome: his Tome defined Christ's two natures and was acclaimed at the Council of Chalcedon (451) — 'Peter has spoken through Leo.' In 452 he rode out to the Mincio and personally turned Attila back from Rome; three years later he interceded to soften Gaiseric's sack.",
   njclNote:"Two missions define him: Tome → Chalcedon (451), embassy → Attila (452). Prime papal-power evidence.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["attila","gaiseric","valentinian-iii"], powerLinks:[],
   tags:["christianity","religion","fall-of-west"], sources:["Wikipedia: Pope Leo I","Britannica: Saint Leo I"]},
  {id:"alaric-i", displayName:"Alaric I", fullName:"Alaric I (Visigothic king)", alternateNames:["Alaric"], year:370, dynasty:"theodosian",
   role:"Visigoth king; sacker of Rome (410)", bio:"Gothic noble who fought under Theodosius at Frigidus (394), then became the first king of the Visigoths (395). Checked by Stilicho at Pollentia and Verona (402–403), he waited out Stilicho's fall and Honorius's refusals — then took Rome itself for three days in August 410, the city's first sack in eight centuries.",
   njclNote:"410: Alaric & the Visigoths — first sack since Brennus's Gauls (390 BC). Pair with Gaiseric's Vandal sack (455).",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["stilicho","honorius","athaulf"], powerLinks:[],
   tags:["military","fall-of-west"], sources:["Wikipedia: Alaric I","Britannica: Alaric"]},
  {id:"athaulf", displayName:"Athaulf", fullName:"Athaulf (Ataulf, Visigothic king)", alternateNames:["Ataulf","Atawulf"], year:372, dynasty:"theodosian",
   role:"Alaric's successor; married Galla Placidia", bio:"Brother-in-law of Alaric and his successor as Visigothic king (410–415); he carried the Goths into Gaul and married the captive imperial princess Galla Placidia in a Roman ceremony at Narbonne (414). Murdered at Barcelona — his own verdict: he had hoped to replace Romania with Gothia, then learned only Roman law could sustain Gothic strength.",
   njclNote:"The Narbonne wedding (414) — a Goth king marrying Theodosius I's daughter inside a Roman church is the era in miniature.",
   biologicalLinks:[], maritalLinks:["galla-placidia"], adoptiveLinks:[], associateLinks:["alaric-i","honorius"], powerLinks:[],
   tags:["military","fall-of-west","dynasty"], sources:["Wikipedia: Ataulf"]},
  {id:"wallia", displayName:"Wallia", fullName:"Wallia (Visigothic king)", alternateNames:["Walia"], year:385, dynasty:"theodosian",
   role:"Visigoth king; foederati of Aquitaine", bio:"Athaulf's successor (415–418) who returned Galla Placidia to Honorius and campaigned for Rome against the Vandals, Alans, and Sueves in Spain. His reward was the foedus of 418: the Visigoths settled in Aquitania (capital Tolosa/Toulouse) — the first barbarian federate kingdom inside the Empire.",
   njclNote:"418 = the legal settlement that put a Gothic kingdom INSIDE the empire — a hinge point for the West's transformation.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["honorius","galla-placidia","athaulf"], powerLinks:[],
   tags:["military","fall-of-west"], sources:["Wikipedia: Wallia"]},
  {id:"radagaisus", displayName:"Radagaisus", fullName:"Radagaisus", alternateNames:["Radagais"], year:405, dynasty:"theodosian",
   role:"Leader of the great Gothic invasion of 405", bio:"Gothic king who poured over the Alps into Italy in 405/406 with one of the largest barbarian hosts Rome ever faced — ancient writers claim 200,000+. Stilicho trapped and destroyed the army at Fiesole near Florence (August 406); Radagaisus was executed.",
   njclNote:"The invasion BEFORE Alaric's sacks — remember: Stilicho beat him at Fiesole (406), the West's last clean victory.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["stilicho","honorius"], powerLinks:[],
   tags:["military","fall-of-west"], sources:["Wikipedia: Radagaisus"]},
  {id:"gainas", displayName:"Gainas", fullName:"Gainas", alternateNames:["Gaines"], year:399, dynasty:"theodosian",
   role:"Gothic strongman of the Eastern court", bio:"Gothic magister militum who exploited Tribigild's Phrygian revolt (399) to dominate Arcadius's court at Constantinople. The city's anti-Gothic riot of July 400 massacred thousands of his people; fleeing, he was hunted down and killed by the Hun Uldin — his head sent to Constantinople as a gift.",
   njclNote:"Shows the East surviving what killed the West: Constantinople's mob and court purged its own 'Stilicho.'",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["arcadius"], powerLinks:[],
   tags:["military","fall-of-west"], sources:["Wikipedia: Gainas"]},
  {id:"arbogast", displayName:"Arbogast", fullName:"Flavius Arbogastes", alternateNames:["Arbogastes"], year:360, dynasty:"theodosian",
   role:"Frankish general behind Eugenius", bio:"Frankish magister militum of the West under Valentinian II — widely suspected in the young emperor's death (392). He raised the pagan rhetorician Eugenius to the purple and led the last pagan-leaning army of the West; Theodosius I destroyed them at the Frigidus (September 394), after which Arbogast died by suicide or in flight.",
   njclNote:"Frigidus (394) = Theodosius's last victory AND the last pagan military stand — Eugenius was his puppet.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["valentinian-ii","theodosius-i"], powerLinks:[],
   tags:["military","religion","fall-of-west"], sources:["Wikipedia: Arbogast (general)"]},
  {id:"gaiseric", displayName:"Gaiseric", fullName:"Gaiseric (Genseric, Vandal-Alan king)", alternateNames:["Genseric","Geiseric"], year:389, dynasty:"theodosian",
   role:"Vandal king; sacker of Rome (455)", bio:"Lame, cunning Vandal-Alan king (r. 428–477) who ferried his people across the Strait of Gibraltar (429), conquered Roman Africa — Carthage fell in 439, crippling the West's grain and tax base — and built the Mediterranean's only barbarian fleet. In 455 he sacked Rome itself, carrying off Empress Licinia Eudoxia and her daughters.",
   njclNote:"Africa + fleet + the 455 sack: Gaiseric did more structural damage to the West than any single Goth.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["valentinian-iii","aetius","licinia-eudoxia","pope-leo-i","aspar"], powerLinks:[],
   tags:["military","fall-of-west"], sources:["Wikipedia: Genseric","Britannica: Gaiseric"]},
  {id:"boniface", displayName:"Bonifatius (Count of Africa)", fullName:"Bonifatius (comes Africae)", alternateNames:["Boniface","Count Boniface"], year:390, dynasty:"theodosian",
   role:"Count of Africa; Aetius's fatal rival", bio:"Commander who stayed loyal to Galla Placidia through the usurpation of 423–425 and held Africa for the dynasty. The court's feud of Felix–Boniface–Aetius ended at Rimini (432): Boniface won the battle but took a fatal wound — Procopius's tale that he 'invited the Vandals' into Africa is now doubted, but the loss of Africa happened on his watch.",
   njclNote:"The Felix→Boniface→Aetius feud: the West's top generals killing each other while Vandals took Africa.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["aetius","galla-placidia","gaiseric"], powerLinks:[],
   tags:["military","fall-of-west"], sources:["Wikipedia: Bonifatius"]},
  {id:"aspar", displayName:"Ardabur Aspar", fullName:"Flavius Ardabur Aspar", alternateNames:["Aspar"], year:395, dynasty:"theodosian",
   role:"Alan kingmaker of the East", bio:"Alan-born magister militum who dominated the eastern army for a generation, campaigned against Gaiseric's Vandals, and made Leo I emperor (457). An Arian, he could never wear the purple himself; when Leo broke free, Aspar and his son Ardabur were assassinated in the palace (471) — ending Germanic ascendancy at Constantinople.",
   njclNote:"The East's answer to Ricimer — a barbarian kingmaker whose murder (471) let the East keep its army Roman.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["gaiseric"], powerLinks:[],
   tags:["military","fall-of-west"], sources:["Wikipedia: Aspar"]},
  {id:"honoria", displayName:"Justa Grata Honoria", fullName:"Justa Grata Honoria", alternateNames:["Honoria"], year:417, dynasty:"theodosian",
   role:"Princess whose ring summoned Attila", bio:"Sister of Valentinian III, Augusta, and dynastic embarrassment: caught in an affair and forcibly betrothed to the safe senator Flavius Bassus Herculanus (~450). By the most famous account she sent her ring to Attila begging rescue — the Hun claimed her AND half the West as dowry, giving him his pretext for invading Gaul (451).",
   njclNote:"The 'proposal to Attila' story is the juiciest causus belli of the 5th century — know it's Honoria, not Galla Placidia.",
   biologicalLinks:["valentinian-iii","galla-placidia"], maritalLinks:[], adoptiveLinks:[], associateLinks:["attila"], powerLinks:[],
   tags:["dynasty","fall-of-west"], sources:["Wikipedia: Justa Grata Honoria"]},
  {id:"licinia-eudoxia", displayName:"Licinia Eudoxia", fullName:"Licinia Eudoxia", alternateNames:["Eudoxia"], year:422, dynasty:"theodosian",
   role:"Empress carried off to Carthage", bio:"Daughter of Theodosius II and Aelia Eudocia, married to Valentinian III (437) to bind the two courts. Widowed by Petronius Maximus's coup (455) and forced to marry him, she was taken by Gaiseric's Vandals in the sack — with daughters Eudocia and Placidia — to Carthage, ransomed to Constantinople years later; her daughter married Gaiseric's son Huneric.",
   njclNote:"Her 455 captivity literalizes the West's collapse; her daughter's forced Vandal marriage merged the two dynasties.",
   biologicalLinks:["theodosius-ii","aelia-eudocia"], maritalLinks:["valentinian-iii"], adoptiveLinks:[], associateLinks:["gaiseric","galla-placidia"], powerLinks:[],
   tags:["dynasty","fall-of-west","theodosian"], sources:["Wikipedia: Licinia Eudoxia"]},
  {id:"aelia-eudocia", displayName:"Aelia Eudocia", fullName:"Aelia Eudocia (b. Athenais)", alternateNames:["Eudocia","Athenais"], year:401, dynasty:"theodosian",
   role:"Poet-empress of the East", bio:"Athenian philosopher's pagan daughter Athenais, chosen (by Pulcheria) as the learned bride of Theodosius II (421) and baptized Eudocia. A genuine poet — Homeric centos and hagiography — and public rival to Pulcheria, she withdrew to Jerusalem amid scandal (441–443), endowing churches and monasteries until her death (460).",
   njclNote:"Pagan-born, poet-empress, exile in Jerusalem — the cultured counterweight to her sister-in-law Pulcheria.",
   biologicalLinks:["licinia-eudoxia"], maritalLinks:["theodosius-ii"], adoptiveLinks:[], associateLinks:["pulcheria"], powerLinks:[],
   tags:["dynasty","literature","religion","theodosian"], sources:["Wikipedia: Aelia Eudocia"]},

  /* ---- Last Western figures / successor kingdoms ---- */
  {id:"ricimer", displayName:"Ricimer", fullName:"Flavius Ricimer", alternateNames:["Flavius Ricimer"], year:405, dynasty:"western",
   role:"Suevic kingmaker of the West", bio:"Suevo-Gothic magister militum and the real ruler of the West (456–472): he sank the Vandal fleet at Cape Bon (456), then made and unmade emperors — deposing Avitus, raising and executing Majorian (461), installing Libius Severus, and finally besieging Rome to deprive Anthemius (472). He died of plague weeks later.",
   njclNote:"The archetypal puppet-master: he won battles vs Vandals yet spent the West's last strength killing its own emperors.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["gundeobad"], powerLinks:[],
   tags:["military","fall-of-west","western","succession"], sources:["Wikipedia: Ricimer","Britannica: Ricimer"]},
  {id:"aegidius", displayName:"Aegidius", fullName:"Aegidius", alternateNames:["Aegidius of Soissons","King of the Romans"], year:415, dynasty:"western",
   role:"Roman commander of northern Gaul", bio:"Majorian's magister militum per Gallias who refused service to Ricimer's puppet Severus and carved out a Roman enclave around Soissons. He checked the Visigoths at Orléans (463) — Gregory of Tours calls him 'rex Romanorum' — and died, probably poisoned, in 464/465; his realm passed to his son Syagrius.",
   njclNote:"The Domain of Soissons — last Roman holdout in northern Gaul; father of Syagrius, whom Clovis finishes in 486.",
   biologicalLinks:["syagrius"], maritalLinks:[], adoptiveLinks:[], associateLinks:["ricimer","euric"], powerLinks:[],
   tags:["military","fall-of-west","western"], sources:["Wikipedia: Aegidius"]},
  {id:"syagrius", displayName:"Syagrius", fullName:"Syagrius", alternateNames:["King of the Romans","Syagrius of Soissons"], year:430, dynasty:"western",
   role:"Last 'King of the Romans' in Gaul", bio:"Son of Aegidius and last ruler of the Soissons domain — Gregory of Tours's 'King of the Romans.' Clovis destroyed his army at Soissons (486); he fled to the Visigoth Alaric II at Toulouse, was handed over, and executed — conventionally the end of Roman rule in Gaul.",
   njclNote:"486, Soissons: Clovis eliminates the last Roman enclave — a cleaner 'fall of the West' marker than 476 itself for Gaul.",
   biologicalLinks:["aegidius"], maritalLinks:[], adoptiveLinks:[], associateLinks:["clovis","euric"], powerLinks:[],
   tags:["military","fall-of-west","western"], sources:["Wikipedia: Syagrius"]},
  {id:"euric", displayName:"Euric", fullName:"Euric (Visigothic king)", alternateNames:["Euric I"], year:415, dynasty:"western",
   role:"Greatest Visigothic king", bio:"Killed his brother Theodoric II and took the Visigothic throne (466–484); the first Germanic king to openly repudiate Roman overlordship, he expanded the Toulouse kingdom over most of Gaul south of the Loire and nearly all of Spain. His Codex Euricianus (~480) is the first surviving Germanic law code, serving Romans and Goths alike.",
   njclNote:"Builder of the biggest Western successor kingdom + first Germanic code — law, not just conquest.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["syagrius","aegidius"], powerLinks:[],
   tags:["military","law","fall-of-west","western"], sources:["Wikipedia: Euric","Britannica: Euric"]},
  {id:"gundeobad", displayName:"Gundobad", fullName:"Gundobad (Burgundian king)", alternateNames:["Gundeobad","Gundobad"], year:452, dynasty:"western",
   role:"Burgundian king and lawgiver", bio:"Ricimer's nephew who served as his uncle's magister militum in Italy (raising the puppet Glycerius, 473), then returned to rule Burgundy from Lyons (~473–516). He issued the Lex Burgundionum for his Roman subjects, fought his brother Godigisel with Clovis's backing (500), and was succeeded by his son Sigismund.",
   njclNote:"Roman officer turned tribal king in one life — and the Burgundian Law code is his monument.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["ricimer","clovis"], powerLinks:[],
   tags:["military","law","western"], sources:["Wikipedia: Gundobad"]},
  {id:"clovis", displayName:"Clovis I", fullName:"Clovis I (Chlodovech, Merovingian king)", alternateNames:["Chlodwig","Chlodovech"], year:466, dynasty:"western",
   role:"Frankish king; founder of France", bio:"Merovingian who united the Franks and made them the West's heirs: beat Syagrius at Soissons (486), the Alamanni at Tolbiac, and the Visigoths at Vouillé (507). Baptized by Remigius (~496/508), he alone among barbarian kings embraced NICENE Christianity — making him the Church's champion and his kingdom, Francia, the seed of France.",
   njclNote:"486 Soissons + Vouillé 507 + Orthodox baptism = the three pillars: he is 'the new Constantine' to medieval France.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["syagrius","gundeobad","theodoric-great"], powerLinks:[],
   tags:["military","religion","western"], sources:["Wikipedia: Clovis I","Britannica: Clovis"]},
  {id:"orestes", displayName:"Orestes", fullName:"Orestes", alternateNames:["Orestes (patrician)"], year:440, dynasty:"western",
   role:"Attila's former secretary; father of the last emperor", bio:"Romanized Pannonian who had served as Attila's notarius (secretary), then became Julius Nepos's magister militum — and promptly deposed him to crown his own teenage son Romulus Augustulus (475). When he refused the foederati a third of Italy's land, they mutinied under Odoacer and killed him at Piacenza (476).",
   njclNote:"From Attila's desk to kingmaker — his refusal of the land grant directly triggers Odoacer's coup and 476.",
   biologicalLinks:["romulus-augustulus"], maritalLinks:[], adoptiveLinks:[], associateLinks:["attila","odoacer"], powerLinks:[],
   tags:["military","fall-of-west","western","succession"], sources:["Wikipedia: Orestes (father of Romulus Augustulus)"]},
  {id:"theodoric-great", displayName:"Theodoric the Great", fullName:"Theodoric the Amal (Ostrogothic king)", alternateNames:["Theodoric","Dietrich von Bern"], year:454, dynasty:"western",
   role:"Ostrogoth king of Italy", bio:"Raised a hostage at Constantinople, the Ostrogothic king (r. 471/493–526) was sent by Zeno to take Italy — where he killed Odoacer with his own hand at Ravenna (493). His 33-year rule over 'two peoples,' Goths and Romans, was the most successful successor kingdom: Arian yet tolerant, patron of Boethius and Cassiodorus (whom he also destroyed), builder of Ravenna's finest monuments, and the model of Germanic legend's Dietrich.",
   njclNote:"Killed Odoacer personally (493) and made Ostrogothic Italy WORK — his capital Ravenna still shows his mausoleum and church.",
   biologicalLinks:["amalasuntha"], maritalLinks:[], adoptiveLinks:[], associateLinks:["odoacer","boethius","cassiodorus","clovis"], powerLinks:[],
   tags:["military","western","building"], sources:["Wikipedia: Theodoric the Great","Britannica: Theodoric"]},
  {id:"boethius", displayName:"Boethius", fullName:"Anicius Manlius Severinus Boethius", alternateNames:["Boetius"], year:477, dynasty:"western",
   role:"Philosopher executed by Theodoric", bio:"Last of the Roman senatorial aristocrats: consul (510) and Theodoric's magister officiorum, he labored to transmit Greek logic, music, and mathematics to the West. Accused of treason in the Albinus affair, he wrote The Consolation of Philosophy in prison before his execution (~524/525) — 'last of the Romans, first of the scholastics.'",
   njclNote:"Consolation of Philosophy, written facing death, was the Middle Ages' most-copied secular book.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["theodoric-great","cassiodorus"], powerLinks:[],
   tags:["literature","western"], sources:["Wikipedia: Boethius","Britannica: Boethius"]},
  {id:"cassiodorus", displayName:"Cassiodorus", fullName:"Flavius Magnus Aurelius Cassiodorus Senator", alternateNames:["Cassiodorus Senator"], year:485, dynasty:"western",
   role:"Theodoric's secretary; savior of manuscripts", bio:"Calabrian who served the Ostrogothic court for four decades as quaestor and magister officiorum; his Variae (official letters) are the prime source for Gothic Italy, and his lost Gothic History underlies Jordanes's Getica. Retiring, he founded the Vivarium monastery to copy and translate classics — founding the monastic book-preserving tradition.",
   njclNote:"Two legacies: Variae (inside the Gothic court) and Vivarium (monks copying classics = the survival of Latin literature).",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["theodoric-great","boethius","jordanes"], powerLinks:[],
   tags:["literature","western"], sources:["Wikipedia: Cassiodorus","Britannica: Cassiodorus"]},
  {id:"amalasuntha", displayName:"Amalasuntha", fullName:"Amalasuntha", alternateNames:["Amalaswintha","Amalasunta"], year:495, dynasty:"western",
   role:"Ostrogothic queen regent", bio:"Theodoric the Great's daughter and regent of Italy (526–534) for her son Athalaric; Roman in education and policy, she resisted the Gothic nobles' militarist demands. After Athalaric died she made her cousin Theodahad co-ruler — he imprisoned her on an island in Lake Bolsena and had her strangled in her bath (535), handing Justinian his pretext to invade.",
   njclNote:"Her murder (535) IS the casus belli for Justinian's Gothic War — the event that undid her father's Italy.",
   biologicalLinks:["theodoric-great"], maritalLinks:[], adoptiveLinks:[], associateLinks:["justinian-i"], powerLinks:[],
   tags:["western","dynasty","succession"], sources:["Wikipedia: Amalasuntha","Britannica: Amalasuntha"]},
  {id:"totila", displayName:"Totila", fullName:"Totila (Baduila, Ostrogothic king)", alternateNames:["Baduila"], year:505, dynasty:"western",
   role:"Last great Ostrogothic king", bio:"Chosen king in 541, he undid Belisarius's reconquest: retook nearly all Italy, twice captured Rome itself (546, 550 — emptying it once of inhabitants), and won grudging praise even from Procopius for generosity to peasants and freed slaves. Narses defeated and mortally wounded him at Taginae (552).",
   njclNote:"Totila vs. Belisarius, then Totila vs. Narses — Taginae (552) broke the Goths; Teia's defeat (553) ended them.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["belisarius","narses","justinian-i"], powerLinks:[],
   tags:["military","western"], sources:["Wikipedia: Totila","Britannica: Totila"]},

  /* ---- Byzantine / Justinianic world ---- */
  {id:"verina", displayName:"Verina", fullName:"Aelia Verina", alternateNames:["Aelia Verina"], year:425, dynasty:"byzantine",
   role:"Scheming empress of the East", bio:"Wife of Leo I and mother of Ariadne; a plotting force at court — she crowned her brother Basiliscus in a brief coup (475–476), conspired against son-in-law Zeno, and was finally besieged at Papirius in Isauria, where she starved to death (484).",
   njclNote:"The court soap-opera node: wife of Leo I → mother of Ariadne → sister of usurper Basiliscus → foe of Zeno.",
   biologicalLinks:["ariadne"], maritalLinks:[], adoptiveLinks:[], associateLinks:[], powerLinks:[],
   tags:["dynasty","byzantine-continuity","succession"], sources:["Wikipedia: Verina"]},
  {id:"ariadne", displayName:"Aelia Ariadne", fullName:"Aelia Ariadne", alternateNames:["Ariadne"], year:450, dynasty:"byzantine",
   role:"Empress who chose two emperors", bio:"Daughter of Leo I and Verina; married the Isaurian Zeno, then — after his death in 491 — personally selected the elderly official Anastasius I and married him, making him emperor. Augusta for over four decades until her death (515).",
   njclNote:"Her two marriages literally selected two emperors (Zeno, Anastasius) — a dynasty carried by a single woman.",
   biologicalLinks:["verina"], maritalLinks:[], adoptiveLinks:[], associateLinks:[], powerLinks:[],
   tags:["dynasty","byzantine-continuity","succession"], sources:["Wikipedia: Ariadne (empress)"]},
  {id:"narses", displayName:"Narses", fullName:"Narses", alternateNames:["Narses the eunuch"], year:478, dynasty:"byzantine",
   role:"Justinian's eunuch general", bio:"Armenian court eunuch and imperial treasurer who proved one of history's great generals: he helped crush the Nika rioters (532), served in Italy, then returned in 551 to destroy the Ostrogoths — killing Totila at Taginae (552) and Teia at Mons Lactarius (553) — and held Italy as exarch at Ravenna.",
   njclNote:"Belisarius STARTED the Gothic war; Narses FINISHED it (552–553). The eunuch general is an exam-favorite contrast.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["justinian-i","belisarius","totila"], powerLinks:[],
   tags:["military","byzantine-continuity"], sources:["Wikipedia: Narses","Britannica: Narses"]},
  {id:"procopius", displayName:"Procopius", fullName:"Procopius of Caesarea", alternateNames:["Procopius of Caesarea"], year:500, dynasty:"byzantine",
   role:"Historian of Justinian (and his secret scourge)", bio:"Legal secretary to Belisarius through the Persian, Vandal, and Gothic campaigns; his History of the Wars is the indispensable eyewitness account, On Buildings the catalog of Justinian's works — and the posthumous Anecdota (Secret History) is a scandalous inversion denouncing Justinian as a demon, Theodora as a monster, and Belisarius as a cuckold.",
   njclNote:"Same author, three voices: official Wars, flattering Buildings, venomous Secret History — THE primary-source lesson for 6th century.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["belisarius","justinian-i","theodora"], powerLinks:[],
   tags:["literature","byzantine-continuity"], sources:["Wikipedia: Procopius","Britannica: Procopius"]},
  {id:"jordanes", displayName:"Jordanes", fullName:"Jordanes (Jornandes)", alternateNames:["Jornandes"], year:500, dynasty:"byzantine",
   role:"Historian of the Goths", bio:"Gothic-descended writer at Constantinople whose Getica (~551), epitomizing Cassiodorus's lost Gothic History, is our chief source for early Gothic history — including the fullest surviving account of Attila and the Catalaunian battle; his Romana is a universal chronicle.",
   njclNote:"Without Jordanes (via Cassiodorus) we'd know almost nothing of Gothic origins or Attila's character and court.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["cassiodorus","justinian-i"], powerLinks:[],
   tags:["literature","byzantine-continuity"], sources:["Wikipedia: Jordanes","Britannica: Jordanes"]},
  {id:"tribonian", displayName:"Tribonian", fullName:"Tribonian (Tribonianus)", alternateNames:["Tribonianus"], year:490, dynasty:"byzantine",
   role:"Architect of the Corpus Juris Civilis", bio:"Justinian's brilliant quaestor sacri palatii (from 529) who chaired the law commission producing the Codex Justinianus (529, revised 534), the Digest or Pandects (533 — 50 books of classical jurisprudence), and the Institutes (533). A Nika-riot target briefly dismissed (532), he died of the plague (~542/545).",
   njclNote:"Justinian's Code is famous; TRIBONIAN actually compiled it — name the jurist, not just the emperor.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["justinian-i","procopius"], powerLinks:[],
   tags:["law","byzantine-continuity"], sources:["Wikipedia: Tribonian","Britannica: Tribonian"]},
  {id:"khosrow-i", displayName:"Khosrow I", fullName:"Khosrow I Anushirvan (Sasanian Shahanshah)", alternateNames:["Chosroes","Khosrau","Anushirvan"], year:512, dynasty:"byzantine",
   role:"Justinian's Persian rival", bio:"Greatest Sasanian king of kings (r. 531–579): he sacked Antioch (540) and deported its people to his model city 'Better-than-Antioch-of-Khosrow,' fought Justinian to the 'Eternal' and Fifty-Year Peaces, reformed taxation and the army, and sheltered Athens' last philosophers after 529 — remembered in Persian tradition as Anushirvan the Just.",
   njclNote:"The eastern mirror of Justinian — their duel (and the Antioch sack of 540) defines 6th-century geopolitics.",
   biologicalLinks:[], maritalLinks:[], adoptiveLinks:[], associateLinks:["justinian-i","belisarius"], powerLinks:[],
   tags:["military","byzantine-continuity"], sources:["Wikipedia: Khosrow I","Britannica: Khosrow I"]}
]);
